version: "3.9"
   
services:
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/code:delegated
    ports:
      - "5000:5000"

  redis:
      image: "redis:alpine"
      command: redis-server
      ports: 
          - "6379:6379"
    