# Generated by Django 4.0.3 on 2022-08-09 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do comando')),
                ('plataform', models.CharField(max_length=255, verbose_name='Plataforma de Execução')),
                ('script', models.TextField(max_length=512, verbose_name='Script de execução')),
            ],
            options={
                'verbose_name': 'Comando',
                'verbose_name_plural': 'Comandos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do dispositivo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customuser', verbose_name='Usuário/Dono')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Intents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da intenção')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.commands', verbose_name='Comando')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.devices', verbose_name='Dispositivos')),
            ],
            options={
                'verbose_name': 'Intenção',
                'verbose_name_plural': 'Intenções',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionIntentsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.intents', verbose_name='Intent')),
            ],
            options={
                'verbose_name': 'Log de execução',
                'verbose_name_plural': 'Logs de execução',
                'ordering': ['id'],
            },
        ),
    ]
